Blog_SaoPaulino/Blog_SaoPaulino/urls.py
from unicodedata import name

from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include('app_blog.urls')),
    path('account/', include('app_login.urls')),
    
]

Blog_SaoPaulino/app_blog/urls.py
from os import path
from django.urls import path

from app_blog import views

app_name = 'blog'

urlpatterns = [
    path('', views.lista_blog, name='lista_blog')
]

Blog_SaoPaulino/app_login/urls.py
from django.urls import path

from app_login import views

app_name = 'login'

urlpatterns = [
    path('signup/', views.sign_up, name='signup'),
    path('login/', views.pagina_login, name='login')
]

Blog_SaoPaulino/app_blog/models.py
from pyexpat import model
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class Blog(models.Model):
    autor = models.ForeignKey(User, on_delete=models.CASCADE,
                              related_name='post_autor')
    blog_titulo = models.CharField(max_length=264, verbose_name='Digite um título')
    slug = models.SlugField(max_length=264, unique=True)
    blog_conteudo = models.TextField(verbose_name='Escreva algo')
    blog_imagem = models.ImageField(upload_to='blog_images',
                                    verbose_name='Imagem do Blog')
    data_publicacao = models.DateTimeField(auto_now_add=True)
    data_atualizacao = models.DateTimeField(auto_now=True)
    
    def __str__(self):
        return self.blog_titulo
    
class Comentario(models.Model):
    blog = models.ForeignKey(Blog, on_delete=models.CASCADE, 
                             related_name='blog_comentario')
    usuario = models.ForeignKey(User, on_delete=models.CASCADE, 
                                related_name='usuario_comentario')
    comentario = models.TextField()
    data_comentario = models.DateTimeField(auto_now_add=True)
    
class Gostei(models.Model):
    blog = models.ForeignKey(Blog, on_delete=models.CASCADE, 
                             related_name='gostei_blog')
    usuario = models.ForeignKey(User, on_delete=models.CASCADE, 
                                related_name='usuarios_gostaram')

Blog_SaoPaulino/app_login/models.py
from distutils.command.upload import upload
from django.db import models
from django.contrib.auth.models import User
# Create your models here.

class Perfil(models.Model):
    usuario = models.OneToOneField(User, related_name='perfil', on_delete=models.CASCADE)
    foto_perfil = models.ImageField(upload_to='foto_perfil')
    

Blog_SaoPaulino/Blog_SaoPaulino/views.py
from django.http import HttpResponse 
from django.shortcuts import render

Blog_SaoPaulino/app_blog/views.py
from django.shortcuts import render

# Create your views here.

def lista_blog(request):
    return render(request,'app_blog/lista_blog.html', context={})

Blog_SaoPaulino/app_login/views.py
from django.shortcuts import render, HttpResponseRedirect
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import login, authenticate, logout
from django.urls import reverse
# Create your views here.


def sign_up(request):
    form = UserCreationForm()
    registrado = False
    if request.method == 'POST':
        form = UserCreationForm(data=request.POST)
        if form.is_valid():
            form.save()
            registrado = True
    context = {'form':form,'registrado': registrado}
    return render(request, 'app_login/signup.html', context)

def pagina_login(request):
    form = AuthenticationForm()
    if request.method == 'POST':
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(username=username, password=password)
            if user is not None:
                login(request, user)
                return HttpResponseRedirect(reverse('blog:lista_blog'))
    
    return render(request, 'app_login/login.html', context={'form':form})

Blog_SaoPaulino/templates/app_blog/lista_blog.html
{% extends 'base.html' %}

{% block title %}
  
{% endblock title %}

{% block body_block %}
  <h1>Lista de blogs</h1>
  
{% endblock body_block %}

Blog_SaoPaulino/templates/app_login/login.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title %}
  Login
{% endblock title %}

{% block body_block %}
    <h1>Login em sua Conta</h1>
    <form action="" method="post">
        {% csrf_token %}
        {{form|crispy}}
        <button type="submit" class="btn btn-primary btn-sm">Login</button>
    </form>
{% endblock %}

Blog_SaoPaulino/templates/app_login/signup.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title %}
  Registro
{% endblock title %}

{% block body_block %}

    {% if registrado %}
      <div class="alert alert-success">
        Conta criada com Sucesso <a href="{% url 'login:login'%}">Login</a>
      </div>

    {% else %}
        <h1>Crie uma Nova Conta</h1>
        <form action="" method="post">
            {% csrf_token %}
            {{form|crispy}}
            <br><br>
            <button type="submit" class="btn btn-success btn-sm">Criar Conta</button>
        </form>
            <br>
        <p>Já possui uma conta?</p> <a href="{% url 'login:login'%}">Login</a>

    {% endif %}
   
  
{% endblock body_block %}

Blog_SaoPaulino/templates/base.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.8.0/font/bootstrap-icons.css">

    <title>
        {% block title %}
            Blogs Page
        {% endblock title %}

    </title>
  </head>
  <body>
    
    <nav class="navbar navbar-expand-sm bg-danger navbar-dark">
        <ul class="navbar-nav">
            <li class="nav-item active"> 
                <a class="nav-link" href="{% url 'blog:lista_blog' %}">Home</a>
            </li>
            <li class="nav-item active"> 
              <a class="nav-link" href="{% url 'login:signup' %}">Registrar</a>
          </li>
            
        </ul>
        <form class="d-flex" role="search">
            <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
            <button class="btn btn-outline-success" type="submit">Search</button>
          </form>
    </nav>

    

    <div class="container" style="padding-top 20px;">
      {% block body_block %}
      {% endblock body_block %}
    </div>
    


    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js" integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js" integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13" crossorigin="anonymous"></script>
    -->
  </body>
</html>

Blog_SaoPaulino/templates/base2.html
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Hugo 0.101.0">
    <title>Fixed top navbar example · Bootstrap v5.2</title>

    <link rel="canonical" href="https://getbootstrap.com/docs/5.2/examples/navbar-fixed/">

    

    

<link href="/docs/5.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">

    <!-- Favicons -->
<link rel="apple-touch-icon" href="/docs/5.2/assets/img/favicons/apple-touch-icon.png" sizes="180x180">
<link rel="icon" href="/docs/5.2/assets/img/favicons/favicon-32x32.png" sizes="32x32" type="image/png">
<link rel="icon" href="/docs/5.2/assets/img/favicons/favicon-16x16.png" sizes="16x16" type="image/png">
<link rel="manifest" href="/docs/5.2/assets/img/favicons/manifest.json">
<link rel="mask-icon" href="/docs/5.2/assets/img/favicons/safari-pinned-tab.svg" color="#712cf9">
<link rel="icon" href="/docs/5.2/assets/img/favicons/favicon.ico">
<meta name="theme-color" content="#712cf9">


    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }

      .b-example-divider {
        height: 3rem;
        background-color: rgba(0, 0, 0, .1);
        border: solid rgba(0, 0, 0, .15);
        border-width: 1px 0;
        box-shadow: inset 0 .5em 1.5em rgba(0, 0, 0, .1), inset 0 .125em .5em rgba(0, 0, 0, .15);
      }

      .b-example-vr {
        flex-shrink: 0;
        width: 1.5rem;
        height: 100vh;
      }

      .bi {
        vertical-align: -.125em;
        fill: currentColor;
      }

      .nav-scroller {
        position: relative;
        z-index: 2;
        height: 2.75rem;
        overflow-y: hidden;
      }

      .nav-scroller .nav {
        display: flex;
        flex-wrap: nowrap;
        padding-bottom: 1rem;
        margin-top: -1px;
        overflow-x: auto;
        text-align: center;
        white-space: nowrap;
        -webkit-overflow-scrolling: touch;
      }
    </style>

    
    <!-- Custom styles for this template -->
    <link href="navbar-top-fixed.css" rel="stylesheet">
  </head>
  <body>
    
<nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">Fixed navbar</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarCollapse">
      <ul class="navbar-nav me-auto mb-2 mb-md-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="#">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Link</a>
        </li>
        <li class="nav-item">
          <a class="nav-link disabled">Disabled</a>
        </li>
      </ul>
      <form class="d-flex" role="search">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>

<main class="container">
  <div class="bg-light p-5 rounded">
    <h1>Navbar example</h1>
    <p class="lead">This example is a quick exercise to illustrate how fixed to top navbar works. As you scroll, it will remain fixed to the top of your browser’s viewport.</p>
    <a class="btn btn-lg btn-primary" href="/docs/5.2/components/navbar/" role="button">View navbar docs &raquo;</a>
  </div>
</main>


    <script src="/docs/5.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-A3rJD856KowSb7dwlZdYEkO39Gagi7vIsF0jrRAoQmDKKtQBHUuLZ9AsSv4jD4Xa" crossorigin="anonymous"></script>

      
  </body>
</html>